### ISSUE TITLE
The tool will crash when the point cloud data too big

### ISSUE THREAD

**Issue by ivan8409023** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#57]
Hi, really thank you for providing such a good tool.
I am going to use the tool to label some large point cloud data, each of  the data might over 1 gigabyte, and after I input the data into the tool, it just don't have any response then the tool crash, so I test smaller data like 300 MB and it can work. I am curious about how large the tool can handle, or is there some setting that I can adjust but i miss? Could you please help with this?
Thank you

**Comment by dmandrioli** [comment]
Hi, thanks for your feedback. Not easy to answer your question, the tool can handle as much as your machine can which is depending on your GPU, memory, etc... :)

To evaluate the room for improvement of the tool, you can try to open your large files in the PCD sample of Three.js: https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_pcd.html

Since the tool rely on Three.js, if this very simple PCD loader sample also crashes with your big files, it won't be possible to do much more on the tool. Otherwise, it will make sense to investigate for optimization.
