### ISSUE TITLE
Label Output Format 

### ISSUE THREAD

**Issue by ncamous** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#81]
Hello,
Thank you for putting at disposition this great tool! 

i was wondering under which format you write the labels in the output pcd file (as an int, uint32?) Im trying to load a already labelled map in the tool (in pcd format) yet when i add the labels it doesnt display it.

**Comment by dmandrioli** [comment]
Hi thanks for your positive feedback.

The tool only output text PCD files so it's just integers written as string. to load a pre-labeled PCD file you need a 'label' column with integers matching the position of the class in the classes set. But this will work only the first time your open a file because once edited, labels are stored in database. [Reference](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#pcd-support)
